FROM node:latest as builder

# Create Work Directory & npm Installed

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@2.1.3 -g --silent

# Copy SourceCode to Work Directory & Build

COPY . /usr/src/app
RUN npm run build



FROM nginx:1.13.9-alpine

# Delete Default Nginx Configure & Copy My-app Configure to Nginx Config
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

# 빌드 산출물을 Nginx 샘플 앱이 사용한 폴더로 이동
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# Open Port 80
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

